<x-filament-panels::page>
    <section class="backoffice-page-intro" aria-labelledby="waste-catalog-title">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div>
        <p class="text-sm font-semibold text-forest-700">Data master</p>
        <h2 id="waste-catalog-title" class="mt-1 text-2xl font-bold text-deep-green">Katalog Sampah</h2>
        <p class="mt-2 max-w-2xl text-sm leading-6 text-text-secondary">Kelola kategori, jenis, kondisi, satuan, dan harga dari satu area yang mudah ditemukan.</p>
            </div>
            <img src="{{ asset('images/landing/mascot-3.png') }}" alt="Maskot badak memilah kategori dan jenis sampah" class="h-24 w-24 self-end object-contain sm:h-28 sm:w-28 sm:self-auto">
        </div>
    </section>

    <p id="waste-catalog-navigation-help" class="mt-6 text-sm leading-6 text-text-secondary">Gunakan tombol Tab untuk memfokuskan navigasi, lalu geser secara horizontal bila seluruh bagian belum terlihat.</p>
    <nav class="mt-2 overflow-x-auto border-b border-border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2" aria-label="Bagian katalog sampah" aria-describedby="waste-catalog-navigation-help" tabindex="0">
        <div class="flex min-w-max gap-2 sm:gap-4">
            @if ($canViewCategories)<a href="{{ \App\Filament\Resources\WasteMaster\Models\WasteCategories\WasteCategoryResource::getUrl('index') }}" @class(['inline-flex min-h-12 items-center gap-2 border-b-2 px-3 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2', 'border-primary-600 bg-primary-50 text-primary-800' => request()->routeIs('filament.backoffice.resources.waste-master.models.waste-categories.*'), 'border-transparent text-text-secondary hover:border-primary-500 hover:bg-primary-50 hover:text-primary-800' => ! request()->routeIs('filament.backoffice.resources.waste-master.models.waste-categories.*')]) @if (request()->routeIs('filament.backoffice.resources.waste-master.models.waste-categories.*')) aria-current="page" @endif><x-filament::icon icon="heroicon-o-squares-2x2" class="size-5 shrink-0" aria-hidden="true" /><span>Kategori</span></a>@endif
            @if ($canViewTypes)<a href="{{ \App\Filament\Resources\WasteMaster\Models\WasteTypes\WasteTypeResource::getUrl('index') }}" @class(['inline-flex min-h-12 items-center gap-2 border-b-2 px-3 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2', 'border-primary-600 bg-primary-50 text-primary-800' => request()->routeIs('filament.backoffice.resources.waste-master.models.waste-types.*'), 'border-transparent text-text-secondary hover:border-primary-500 hover:bg-primary-50 hover:text-primary-800' => ! request()->routeIs('filament.backoffice.resources.waste-master.models.waste-types.*')]) @if (request()->routeIs('filament.backoffice.resources.waste-master.models.waste-types.*')) aria-current="page" @endif><x-filament::icon icon="heroicon-o-tag" class="size-5 shrink-0" aria-hidden="true" /><span>Jenis</span></a>@endif
            @if ($canViewConditions)<a href="{{ \App\Filament\Resources\WasteMaster\Models\WasteConditions\WasteConditionResource::getUrl('index') }}" @class(['inline-flex min-h-12 items-center gap-2 border-b-2 px-3 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2', 'border-primary-600 bg-primary-50 text-primary-800' => request()->routeIs('filament.backoffice.resources.waste-master.models.waste-conditions.*'), 'border-transparent text-text-secondary hover:border-primary-500 hover:bg-primary-50 hover:text-primary-800' => ! request()->routeIs('filament.backoffice.resources.waste-master.models.waste-conditions.*')]) @if (request()->routeIs('filament.backoffice.resources.waste-master.models.waste-conditions.*')) aria-current="page" @endif><x-filament::icon icon="heroicon-o-clipboard-document-check" class="size-5 shrink-0" aria-hidden="true" /><span>Kondisi</span></a>@endif
            @if ($canViewPrices)<a href="{{ \App\Filament\Resources\WasteMaster\Models\WastePrices\WastePriceResource::getUrl('index') }}" @class(['inline-flex min-h-12 items-center gap-2 border-b-2 px-3 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2', 'border-primary-600 bg-primary-50 text-primary-800' => request()->routeIs('filament.backoffice.resources.waste-master.models.waste-prices.*'), 'border-transparent text-text-secondary hover:border-primary-500 hover:bg-primary-50 hover:text-primary-800' => ! request()->routeIs('filament.backoffice.resources.waste-master.models.waste-prices.*')]) @if (request()->routeIs('filament.backoffice.resources.waste-master.models.waste-prices.*')) aria-current="page" @endif><x-filament::icon icon="heroicon-o-banknotes" class="size-5 shrink-0" aria-hidden="true" /><span>Harga</span></a>@endif
            @if ($canViewUnits)<a href="{{ \App\Filament\Resources\WasteMaster\Models\WasteUnits\WasteUnitResource::getUrl('index') }}" @class(['inline-flex min-h-12 items-center gap-2 border-b-2 px-3 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2', 'border-primary-600 bg-primary-50 text-primary-800' => request()->routeIs('filament.backoffice.resources.waste-master.models.waste-units.*'), 'border-transparent text-text-secondary hover:border-primary-500 hover:bg-primary-50 hover:text-primary-800' => ! request()->routeIs('filament.backoffice.resources.waste-master.models.waste-units.*')]) @if (request()->routeIs('filament.backoffice.resources.waste-master.models.waste-units.*')) aria-current="page" @endif><x-filament::icon icon="heroicon-o-scale" class="size-5 shrink-0" aria-hidden="true" /><span>Satuan</span></a>@endif
        </div>
    </nav>
</x-filament-panels::page>
